---
# handlers file for roles/webserver
- name: Enable Apache
  ansible.builtin.service:
    name: apache2
    enabled: true
    state: started
- name: Install Webserver Subcomponents
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  loop:
    - php
    - php-mysql
    - libapache2-mod-php

- name: Restart Apache
  ansible.builtin.service:
    name: apache2
    state: restarted

- name: Enable new site
  ansible.builtin.command:
    cmd: /usr/sbin/a2ensite {{ ansible_hostname }}
  changed_when: true

- name: Configure SSL for Apache
  ansible.builtin.command:
    cmd: a2enmod ssl
  changed_when: true

- name: Remove default site
  ansible.builtin.command:
    cmd: "/usr/sbin/a2dissite 000-default"
  changed_when: true

- name: Restart Firewall
  ansible.builtin.service:
    name: ufw
    state: restarted
