all:
  hosts:
  children:
    controlhosts:
      hosts:
        controlnode1:
          ansible_host: 10.129.25.54
    dbserver:
      hosts:
        node3:
          ansible_host: 10.129.25.196
    loadbalancers:
      hosts:
        node3:
          ansible_host: 10.129.25.196
    webservers:
      hosts:
        node1:
          ansible_host: 10.129.25.194
        node2:
          ansible_host: 10.129.25.195
    routers:
      hosts:
        router:
          ansible_host: 10.129.25.8
