---
- name: Update all device packages
  hosts: all:!router
  become: true

  roles:
    - common

- name: Webservers installeren
  hosts: webservers
  become: true

  roles:
    - webserver

- name: Mysql server installeren
  hosts: dbserver
  become: true
  roles:
    - database

- name: Setup website
  hosts: webservers
  become: true
  roles:
    - website-github

- name: Setup Loadbalancer
  hosts: loadbalancers
  become: true
  roles:
    - loadbalancer

- name: Diverse
  hosts: webservers:dbserver:controlhosts
  become: true
  roles:
    - varia

- name: Ensure SSH config available for routers
  hosts: controlhosts
  become: true
  tasks:
    - name: Setup config rules
      ansible.builtin.lineinfile:
        path: /etc/ssh/ssh_config
        line: "{{ item }}"
        state: present
      loop:
        - KexAlgorithms +diffie-hellman-group14-sha1
        - Ciphers +aes256-cbc,aes192-cbc,aes128-cbc,3des-cbc
        - HostKeyAlgorithms +ssh-rsa
        - PubkeyAcceptedAlgorithms +ssh-rsa
      notify:
        - Restart ssh
  handlers:
    - name: Restart ssh
      ansible.builtin.service:
        name: sshd
        state: restarted

# rhel specific issue with libcrypto
- name: Set crypto policy
  hosts: controlhosts
  become: true
  gather_facts: false
  tasks:
    - name: Set to LEGACY
      ansible.builtin.command:
        cmd: "update-crypto-policies --set LEGACY"
      changed_when: true

- name: Ensure pylibssh
  hosts: controlhosts
  become: true
  tasks:
    - name: Install pip
      ansible.builtin.dnf:
        name: "python3-pip"
        state: latest
    - name: Install pylibssh
      ansible.builtin.pip:
        name: ansible-pylibssh

- name: Cisco show version example
  hosts: routers
  roles:
    - routerconfig

- name: Reet crypto policy
  hosts: controlhosts
  become: true
  gather_facts: false
  tasks:
    - name: Set to DEFAULT
      ansible.builtin.command:
        cmd: "update-crypto-policies --set DEFAULT"
      changed_when: true
