---
- name: Setup SSH keys
  hosts: all:!router
  become: true

  roles:
    - setupssh

- name: Update all device packages
  hosts: all:!router
  become: true

  roles:
    - common

- name: Webservers installeren
  hosts: webservers

  roles:
    - webserver
