---
collections:
- name: ansible.netcommon
  version: 5.1.0
- name: ansible.posix
  version: 1.5.2
- name: ansible.utils
  version: 2.9.0
- name: cisco.ios
  version: 4.5.0
- name: community.crypto
  version: 2.12.0
- name: community.general
  version: 6.6.0
- name: community.mysql  
  version: 3.6.0