---
# tasks file for roles/loadbalancer
- name: Install Nginx
  ansible.builtin.dnf:
    name: "nginx"
  notify:
    - Enable nginx

- name: Enable firewall
  ansible.posix.firewalld:
    zone: public
    service: http
    permanent: true
    state: enabled
  notify:
    - Restart Firewall

- name: Enable httpd on selinux
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true

- name: Copy configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '644'
    owner: root
    group: root
