---
# tasks file for roles/database
- name: Install Mysql
  ansible.builtin.dnf:
    name: mysql-server
    state: latest
  notify:
    - Enable Mysql Server

- name: Open firewall
  ansible.posix.firewalld:
    source: "{{ item }}/8"
    permanent: true
    state: enabled
  with_items:
    - "{{ groups['webservers'] | map('extract', hostvars, ['ansible_host']) }}"

- name: Ensure pip installed
  ansible.builtin.dnf:
    name: python3-pip
    state: present

- name: Ensure pymysql installed
  ansible.builtin.pip:
    name: "pymysql"
    state: present

- name: Create database users
  community.mysql.mysql_user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    priv: '*.*:ALL'
    state: present
  with_items: "{{ database_users }}"
  no_log: true

- name: Create Database
  community.mysql.mysql_db:
    name: "{{ item.database }}"
    login_user: "{{ item.username }}"
    login_password: "{{ item.password }}"
    state: present
  with_items: "{{ databases }}"
  no_log: true

- name: Run user query
  community.mysql.mysql_query:
    login_db: "{{ item.database }}"
    login_user: "{{ item.username }}"
    login_password: "{{ item.password }}"
    query: "select user, host, password_last_changed from mysql.user"
  with_items: "{{ databases }}"
  register: users_from_db
  no_log: true

- name: Show users in dbserver
  ansible.builtin.debug:
    msg: "user: {{ item.user }} changed password at {{ item.password_last_changed }} @{{ item.host }}"
  with_items: "{{ users_from_db.results[0].query_result }}"
  loop_control:
    label: "{{ item.user }}"
