---
# tasks file for roles/database
- name: Install Mysql
  ansible.builtin.dnf:
    name: mysql-server
    state: latest
  notify:
    - Enable Mysql Server

- name: Open firewall
  ansible.posix.firewalld:
    source: "{{ item }}/8"
    permanent: true
    state: enabled
  with_items:
    - "{{ groups['webservers'] | map('extract', hostvars, ['ansible_host']) }}"
