---
# tasks file for roles/common
- name: Update and upgrade software DNF
  ansible.builtin.dnf:
    name: "*"
    update_cache: true
    state: latest
  when: package_manager == 'dnf'
- name: Update and upgrade software APT
  ansible.builtin.apt:
    name: "*"
    update_cache: true
    state: latest
  when: package_manager == 'apt'
- name: Enable SSH
  ansible.builtin.service:
    name: sshd
    state: started
    enabled: true
- name: Enable firewalld
  ansible.builtin.service:
    name: "{{ firewall_type }}"
    state: restarted
    enabled: true
